// sidebars.js
// Docusaurus v2/v3 compatible

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      collapsed: false,
      link: { type: 'doc', id: '00-overview/00-intro' },
      items: [{ type: 'autogenerated', dirName: '00-overview' }],
    },
    {
      type: 'category',
      label: 'NAP 9 Covenant',
      collapsible: false,
      collapsed: false,
      link: { type: 'doc', id: '10-nap9/00-intro' },
      items: [{ type: 'autogenerated', dirName: '10-nap9' }],
    },
    {
      type: 'category',
      label: 'Operational Guides',
      collapsible: false,
      collapsed: false,
      link: { type: 'doc', id: '30-guides/00-intro' },
      items: [{ type: 'autogenerated', dirName: '30-guides' }],
    },
    {
      type: 'category',
      label: 'Philosophy & Rationale',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '40-philosophy/00-intro' },
      items: [{ type: 'autogenerated', dirName: '40-philosophy' }],
    },
    {
      type: 'category',
      label: 'Meta',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '90-meta/00-intro' },
      items: [{ type: 'autogenerated', dirName: '90-meta' }],
    },
  ],
};

module.exports = sidebars;
